name: Automated Commit

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  update_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name 'SoroushMoradi'
          git config --global user.email 'jooyandeazadi@gmail.com'

      - name: Update TIMESTAMP.txt
        run: |
          echo "Last updated: $(date)" > TIMESTAMP.txt

      - name: Commit and push changes
        run: |
          git add TIMESTAMP.txt
          git commit -m "Update timestamp"
          git push
